version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: daily

  - package-ecosystem: "npm"
    directory: "/internal/mode/static/nginx/modules"
    schedule:
      interval: "daily"
