# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: detect-private-key
        exclude: (^examples/|^docs/|.*_test.go$)

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types:
          - javascript

  - repo: local
    hooks:
      - id: golang-diff
        name: create-go-diff
        entry: bash -c 'git diff -p origin/main > /tmp/diff.patch'
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
      - id: golangci-lint
        args: [--new-from-patch=/tmp/diff.patch]

    # Rules are in .markdownlint.json file
    # See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for rule descriptions
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.8.1
    hooks:
    - id: markdownlint-cli2-fix

ci:
  skip: [golang-diff, golangci-lint, prettier]
