{{- if eq .Values.nginxGateway.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  # We only support a single replica for now
  replicas: 1
  selector:
    matchLabels:
    {{- include "nginx-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "nginx-gateway.selectorLabels" . | nindent 8 }}
      {{- if .Values.metrics.enable }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        {{- if .Values.metrics.secure }}
        prometheus.io/scheme: "https"
        {{- end }}
      {{- end }}
    spec:
      containers:
      - args:
        - static-mode
        - --gateway-ctlr-name={{ .Values.nginxGateway.gatewayControllerName }}
        - --gatewayclass={{ .Values.nginxGateway.gatewayClassName }}
        - --config={{ include "nginx-gateway.config-name" . }}
        {{- if .Values.metrics.enable }}
        - --enable-metrics=true
        - --metrics-listen-port={{ .Values.metrics.port }}
        {{- if .Values.metrics.secure  }}
        - --metrics-secure-serving=true
        {{- end }}
        {{- end }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.nginxGateway.image.repository }}:{{ .Values.nginxGateway.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.nginxGateway.image.pullPolicy }}
        name: nginx-gateway
        {{- if .Values.metrics.enable }}
        ports:
        - name: prometheus
          containerPort: {{ .Values.metrics.port }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - KILL
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 102
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-secrets
          mountPath: /etc/nginx/secrets
        - name: nginx-run
          mountPath: /var/run/nginx
      - image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        name: nginx
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-secrets
          mountPath: /etc/nginx/secrets
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-lib
          mountPath: /var/lib/nginx
      serviceAccountName: {{ include "nginx-gateway.serviceAccountName" . }}
      shareProcessNamespace: true
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-conf
        emptyDir: {}
      - name: nginx-secrets
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-lib
        emptyDir: {}
{{- end }}
