apiVersion: v2
name: nginx-kubernetes-gateway
description: NGINX Kubernetes Gateway
type: application
version: 0.1.0
appVersion: 0.6.0
home: https://github.com/nginxinc/nginx-kubernetes-gateway
icon: https://raw.githubusercontent.com/nginxinc/nginx-kubernetes-gateway/tree/v0.6.0/deploy/helm-chart/chart-icon.png
sources:
  - https://github.com/nginxinc/nginx-kubernetes-gateway/tree/v0.6.0/deploy/helm-chart
keywords:
  - kubernetes
  - gateway
  - nginx
maintainers:
  - name: nginxinc
    email: kubernetes@nginx.com
