apiVersion: v2
name: nginx-gateway-fabric
description: NGINX Gateway Fabric
type: application
version: 1.1.0
appVersion: "1.1.0"
home: https://github.com/nginxinc/nginx-gateway-fabric
icon: https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.1.0/deploy/helm-chart/chart-icon.png
sources:
  - https://github.com/nginxinc/nginx-gateway-fabric/tree/v1.1.0/deploy/helm-chart
keywords:
  - kubernetes
  - gateway
  - nginx
maintainers:
  - name: nginxinc
    email: kubernetes@nginx.com
