nginxGateway:
  ## The kind of the NGINX Kubernetes Gateway installation - currently, only deployment is supported.
  kind: deployment
  ## gatewayClassName is the name of the GatewayClass that will be created as part of this release. Every NGINX Gateway
  ## must have a unique corresponding GatewayClass resource. NGINX Kubernetes Gateway only processes resources that
  ## belong to its class - i.e. have the "gatewayClassName" field resource equal to the class.
  gatewayClassName: nginx
  ## The name of the Gateway controller. The controller name must be of the form: DOMAIN/PATH. The controller's domain
  ## is gateway.nginx.org.
  gatewayControllerName: gateway.nginx.org/nginx-gateway-controller
  ## The dynamic configuration for the control plane that is contained in the NginxGateway resource.
  config:
    logging:
      ## Log level. Supported values "info", "debug", "error".
      level: info
  ## The number of replicas of the NGINX Kubernetes Gateway Deployment.
  replicaCount: 1
  ## The configuration for leader election.
  leaderElection:
    ## Enable leader election. Leader election is used to avoid multiple replicas of the NGINX Kubernetes Gateway
    ## reporting the status of the Gateway API resources. If not enabled, all replicas of NGINX Kubernetes Gateway
    ## will update the statuses of the Gateway API resources.
    enable: true
    ## The name of the leader election lock. A Lease object with this name will be created in the same Namespace as
    ## the controller. Autogenerated if not set or set to "".
    lockName: ""

  ## Defines the settings for the control plane readiness probe. This probe returns Ready when the controller
  ## has started and configured NGINX to serve traffic.
  readinessProbe:
    ## Enable the /readyz endpoint on the control plane.
    enable: true
    ## Port in which the readiness endpoint is exposed.
    port: 8081
    ## The number of seconds after the Pod has started before the readiness probes are initiated.
    initialDelaySeconds: 3

  image:
    ## The NGINX Kubernetes Gateway image to use
    repository: ghcr.io/nginxinc/nginx-kubernetes-gateway
    tag: edge
    pullPolicy: Always

  securityContext:
    ## Some environments may need this set to true in order for the control plane to successfully reload NGINX.
    allowPrivilegeEscalation: false

nginx:
  ## The NGINX image to use
  image:
    repository: ghcr.io/nginxinc/nginx-kubernetes-gateway/nginx
    tag: edge
    pullPolicy: Always

serviceAccount:
  annotations: {}
  ## The name of the service account of the NGINX Kubernetes Gateway pods. Used for RBAC.
  ## Autogenerated if not set or set to "".
  # name: nginx-gateway

service:
  ## Creates a service to expose the NGINX Kubernetes Gateway pods.
  create: true
  ## The type of service to create for the NGINX Kubernetes Gateway.
  type: LoadBalancer
  ## The externalTrafficPolicy of the service. The value Local preserves the client source IP.
  externalTrafficPolicy: Local
  ## The annotations of the NGINX Kubernetes Gateway service.
  annotations: {}

  ## A list of ports to expose through the NGINX Kubernetes Gateway service. Update it to match the listener ports from
  ## your Gateway resource. Follows the conventional Kubernetes yaml syntax for service ports.
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https

metrics:
  ## Enable exposing metrics in the Prometheus format.
  enable: true
  ## Set the port where the Prometheus metrics are exposed. Format: [1024 - 65535]
  port: 9113
  ## Enable serving metrics via https. By default metrics are served via http.
  ## Please note that this endpoint will be secured with a self-signed certificate.
  secure: false
