nginxGateway:
  ## The kind of the NGINX Kubernetes Gateway installation - currently, only deployment is supported.
  kind: deployment
  ## gatewayClassName is the name of the GatewayClass that will be created as part of this release. Every NGINX Gateway
  ## must have a unique corresponding GatewayClass resource. NGINX Kubernetes Gateway only processes resources that
  ## belong to its class - i.e. have the "gatewayClassName" field resource equal to the class.
  gatewayClassName: nginx
  ## The name of the Gateway controller. The controller name must be of the form: DOMAIN/PATH. The controller's domain
  ## is gateway.nginx.org.
  gatewayControllerName: gateway.nginx.org/nginx-gateway-controller
  ## The dynamic configuration for the control plane that is contained in the NginxGateway CRD.
  crdConfig:
    name: nginx-gateway-config
    spec:
      logging:
        ## Log level. Supported values "info", "debug", "error".
        level: info

  image:
    ## The NGINX Kubernetes Gateway image to use
    repository: ghcr.io/nginxinc/nginx-kubernetes-gateway
    tag: edge
    pullPolicy: Always

nginx:
  ## The NGINX image to use
  image:
    repository: ghcr.io/nginxinc/nginx-kubernetes-gateway/nginx
    tag: edge
    pullPolicy: Always

serviceAccount:
  annotations: {}
  ## The name of the service account of the NGINX Kubernetes Gateway pods. Used for RBAC.
  ## Autogenerated if not set or set to "".
  # name: nginx-gateway

service:
  ## Creates a service to expose the NGINX Kubernetes Gateway pods.
  create: true
  ## The type of service to create for the NGINX Kubernetes Gateway.
  type: LoadBalancer
  ## The externalTrafficPolicy of the service. The value Local preserves the client source IP.
  externalTrafficPolicy: Local
  ## The annotations of the NGINX Kubernetes Gateway service.
  annotations: {}

  ## A list of ports to expose through the NGINX Kubernetes Gateway service. Update it to match the listener ports from
  ## your Gateway resource. Follows the conventional Kubernetes yaml syntax for service ports.
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
