apiVersion: v2
name: nginx-gateway-fabric
description: NGINX Gateway Fabric
type: application
version: 1.6.0
appVersion: "1.6.0"
kubeVersion: ">= 1.25.0-0"
home: https://github.com/nginx/nginx-gateway-fabric
icon: https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/main/charts/nginx-gateway-fabric/chart-icon.png
sources:
  - https://github.com/nginx/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
keywords:
  - kubernetes
  - gateway
  - nginx
maintainers:
  - name: nginx/nginx-gateway-fabric
    email: kubernetes@nginx.com
