apiVersion: v2
name: nginx-gateway-fabric
description: NGINX Gateway Fabric
type: application
version: 1.2.0
appVersion: "edge"
kubeVersion: ">= 1.25.0-0"
home: https://github.com/nginxinc/nginx-gateway-fabric
icon: https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/main/charts/nginx-gateway-fabric/chart-icon.png
sources:
  - https://github.com/nginxinc/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
keywords:
  - kubernetes
  - gateway
  - nginx
maintainers:
  - name: nginxinc/nginx-gateway-fabric
    email: kubernetes@nginx.com
