name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Golang Environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: stable

      - name: Lint Code
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          args: --timeout 10m0s

  njs-lint:
    name: NJS Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Prettier version
        id: prettier-version
        run: |
          echo "version=$(jq -r .devDependencies.prettier ${{ github.workspace }}/internal/mode/static/nginx/modules/package.json)" >> $GITHUB_OUTPUT

      - name: Run Prettier on NJS code
        id: prettier-run
        uses: rutajdash/prettier-cli-action@9e27606a9e18d40b6b4a2b4159e780241d2fbb3c # v1.0.1
        with:
          config_path: ${{ github.workspace }}/internal/mode/static/nginx/modules/.prettierrc
          file_pattern: ${{ github.workspace }}/internal/mode/static/nginx/modules/**/*.js
          prettier_version: ${{ steps.prettier-version.outputs.version }}

      - name: Prettier Output
        if: failure()
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
          echo "Run \"make njs-fmt\" locally to format the code"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: reviewdog/action-actionlint@6a38513dd4d2e818798c5c73d0870adbb82de4a4 # v1.41.0
        with:
          actionlint_flags: -shellcheck ""

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: DavidAnson/markdownlint-cli2-action@510b996878fc0d1a46c8a04ec86b06dbfba09de7 # v15.0.0
        with:
          config: ${{ github.workspace }}/.markdownlint-cli2.yaml
          globs: "**/*.md"

  chart-lint:
    name: Chart Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Lint chart
        run: make lint-helm

  yaml-lint:
    name: Yaml Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
