name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 2 * * *" # run every day at 02:30 UTC

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 14 days."
          stale-pr-message: "This PR is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 14 days."
          close-issue-message: "This issue was closed because it has been stalled for 14 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 14 days with no activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-all-issue-milestones: true
          exempt-issue-labels: "backlog, backlog candidate, epic"
          operations-per-run: 100
          days-before-stale: 14
          days-before-close: 14
